import Config

# Override logger metadata for development to exclude verbose fields (pid, application, mfa)
config :logger, :console,
  metadata: [
    :request_id,
    :file,
    :line,
    :system_id,
    :killmail_id,
    :operation,
    :step,
    :status,
    :error,
    :duration,
    :source,
    :reason,
    :type,
    :message,
    :stacktrace,
    :timestamp,
    :kind,
    :url,
    :response_time,
    :method,
    :service,
    :endpoint,
    :duration_ms,
    :response_size,
    :query_string,
    :remote_ip,
    :cache,
    :cache_key,
    :cache_type,
    :ttl,
    :namespace,
    :id,
    :killmail_count,
    :count,
    :result,
    :data_source,
    :payload_size_bytes,
    :fresh_kills_fetched,
    :kills_to_process,
    :updates,
    :kills_processed,
    :kills_older,
    :kills_skipped,
    :legacy_kills,
    :no_kills_polls,
    :errors,
    :active_systems,
    :total_polls,
    # WebSocket preload metadata
    :user_id,
    :subscription_id,
    :systems_count,
    :peer_data,
    :user_agent,
    :initial_systems_count,
    :new_systems_count,
    :total_systems_count,
    :removed_systems_count,
    :remaining_systems_count,
    :total_systems,
    :total_kills_sent,
    :limit,
    :total_cached_ids,
    :sample_ids,
    :requested_ids,
    :enriched_found,
    :enriched_missing,
    :failed_samples,
    :killmail_ids,
    :cached_ids_count,
    :subscribed_systems_count,
    :disconnect_reason,
    :connection_duration_seconds,
    :socket_transport,
    :systems,
    :active_connections,
    :kills_sent_realtime,
    :kills_sent_preload,
    :kills_per_minute,
    :connections_per_minute,
    :victim_character,
    :victim_corp,
    :attacker_count,
    :total_value,
    :npc_kill,
    :attempt,
    :max_attempts,
    :remaining_attempts,
    :delay_ms,
    :timeout,
    :request_type,
    :raw_count,
    :parsed_count,
    :enriched_count,
    :since_hours,
    :provided_id,
    :types,
    :groups,
    :file,
    :path,
    :pass_type,
    :hours,
    :limit,
    :max_concurrency,
    :purpose,
    :format,
    :percentage,
    :description,
    :unit,
    :value,
    :count,
    :total,
    :processed,
    :skipped,
    :error,
    :total_killmails_analyzed,
    :format_distribution,
    :system_distribution,
    :ship_distribution,
    :character_distribution,
    :corporation_distribution,
    :alliance_distribution,
    :ship_type_distribution,
    :purpose,
    :sample_index,
    :sample_size,
    :sample_type,
    :sample_value,
    :sample_unit,
    :sample_value,
    :sample_structure,
    :data_type,
    :raw_keys,
    :has_full_data,
    :needs_esi_fetch,
    :byte_size,
    :tasks,
    :group_ids,
    :error_count,
    :total_groups,
    :success_count,
    :type_count,
    :cutoff_time,
    :killmail_sample,
    :required_fields,
    :missing_fields,
    :available_keys,
    :killmail_sample,
    :raw_structure,
    :parsed_structure,
    :enriched_structure,
    :killmail_id,
    :system_id,
    :ship_type_id,
    :character_id,
    :killmail_keys,
    :kill_count,
    :hash,
    :has_solar_system_id,
    :has_kill_count,
    :has_hash,
    :has_killmail_id,
    :has_system_id,
    :has_ship_type_id,
    :has_character_id,
    :has_victim,
    :has_attackers,
    :has_zkb,
    :killmail_keys,
    :parser_type,
    :killmail_hash,
    :raw_structure,
    :recommendation,
    :structure,
    :kill_time,
    :kill_time_type,
    :kill_time_value,
    :cutoff,
    :subscriber_id,
    :system_ids,
    :callback_url,
    :subscription_id,
    :status,
    :error,
    :system_count,
    :has_callback,
    :error_count,
    :success_count,
    :total_subscriptions,
    :active_subscriptions,
    :removed_count,
    :requested_systems,
    :successful_systems,
    :failed_systems,
    :total_systems,
    :system_ids,
    :callback_url,
    :subscription_id,
    :status,
    :kills_count,
    :pubsub_name,
    :pubsub_topic,
    :pubsub_message,
    :pubsub_metadata,
    :pubsub_payload,
    :pubsub_headers,
    :pubsub_timestamp,
    :total_kills,
    :filtered_kills,
    :subscriber_count,
    :total_cached_kills,
    :cache_error,
    :returned_kills,
    :unexpected_response,
    :cached_count,
    :total_kills_sent,
    :kills_type,
    :kills_value,
    :kills_count,
    :client_identifier,
    :enriched_count,
    :unenriched_count,
    :kill_time_range,
    :subscriber_count,
    :subscriber_ids,
    :via_pubsub,
    :via_webhook,
    :subscriber_id,
    :since_hours,
    :callback_url,
    :kills_type,
    :kills_value
  ]

# Enable WebSocket transport logging for development debugging
config :wanderer_kills, WandererKillsWeb.Endpoint,
  http: [port: 4004, ip: {0, 0, 0, 0}],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [],
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/wanderer_kills_web/(live|views)/.*(ex)$",
      ~r"lib/wanderer_kills_web/templates/.*(eex)$"
    ]
  ]

# Enable more detailed WebSocket logging for debugging
config :phoenix, :socket_drainer_timeout, 5_000

# Override socket configuration for development debugging
config :wanderer_kills, WandererKillsWeb.Endpoint, socket_drainer_timeout: 5_000

# Enable detailed logging for Phoenix and transport layers
config :logger, level: :info

# Enable Phoenix debug logs
config :phoenix, :logger, true
config :phoenix, :stacktrace_depth, 20
